Repository FindYou-Kuit/FindYou-Android, pull requests merged in 2025-01, with the labels that each got.

#9 [chore] 프로젝트 구조 수정
  app/src/main/java/com/example/findu/data/datalocal/datasource/DummyLocalDataSource.kt
  app/src/main/java/com/example/findu/data/datalocal/datasourceimpl/DummyLocalDataSourceImpl.kt
  app/src/main/java/com/example/findu/data/dataremote/datasource/DummyRemoteDataSource.kt
  app/src/main/java/com/example/findu/data/dataremote/datasourceimpl/DummyRemoteDataSourceImpl.kt
  app/src/main/java/com/example/findu/data/repositoryimpl/DummyRepositoryImpl.kt
  app/src/main/java/com/example/findu/di/DataSourceModule.kt
Labels: 🐻민서, chore

#11 [init] 컬러 초기세팅
  .idea/compiler.xml
  .idea/misc.xml
  app/src/main/res/values/colors.xml
Labels: 🐶소희, init

#17 [feat] 홈 UI 구현
  .idea/compiler.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/example/findu/presentation/model/HomeRv.kt
  app/src/main/java/com/example/findu/presentation/type/AnimalStateType.kt
  app/src/main/java/com/example/findu/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/home/SpaceDecoration.kt
  app/src/main/java/com/example/findu/presentation/ui/home/adapter/HomeBannerAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/home/adapter/HomeRVAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/res/color/bottom_nav_color.xml
  app/src/main/res/drawable/bg_home_banner_number.xml
  app/src/main/res/drawable/bg_home_banner_rounded_corner.xml
  app/src/main/res/drawable/bg_home_rounded_button.xml
  app/src/main/res/drawable/bg_home_rv.xml
  app/src/main/res/drawable/icon_home_find_report.xml
  app/src/main/res/drawable/icon_home_location.xml
  app/src/main/res/drawable/icon_home_more.xml
  app/src/main/res/drawable/img_findu_logo.png
  app/src/main/res/drawable/img_home_bottom.png
  app/src/main/res/drawable/img_home_top_bar_sample.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_rv.xml
  app/src/main/res/layout/item_home_vp_banner.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 🐻민서, feat

#14 [feat] 신고하기 UI 구현
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/example/findu/presentation/type/report/FeatureType.kt
  app/src/main/java/com/example/findu/presentation/type/report/FurColorType.kt
  app/src/main/java/com/example/findu/presentation/type/report/ReportType.kt
  app/src/main/java/com/example/findu/presentation/type/report/SpeciesType.kt
  app/src/main/java/com/example/findu/presentation/ui/report/MissingReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/WitnessReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportBreedAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportColorAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportFeatureAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportImageAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/report/model/ReportDummys.kt
  app/src/main/java/com/example/findu/presentation/util/ViewUtils.kt
  app/src/main/res/color/button_ai_color.xml
  app/src/main/res/color/button_breed_color.xml
  app/src/main/res/color/button_okay_color.xml
  app/src/main/res/color/button_stroke_color.xml
  app/src/main/res/color/check_box_color.xml
  app/src/main/res/color/check_box_stroke_color.xml
  app/src/main/res/color/chip_color.xml
  app/src/main/res/color/chip_stroke_color.xml
  app/src/main/res/color/radio_button_color.xml
  app/src/main/res/color/radio_button_stroke_color.xml
  app/src/main/res/color/text_okay_color.xml
  app/src/main/res/drawable/bg_actv_breed.xml
  app/src/main/res/drawable/bg_bottom_radius_8_g4.xml
  app/src/main/res/drawable/bg_bottom_radius_8_white.xml
  app/src/main/res/drawable/bg_breed_button.xml
  app/src/main/res/drawable/bg_button_ai.xml
  app/src/main/res/drawable/bg_button_report_okay.xml
  app/src/main/res/drawable/bg_check_box_colors.xml
  app/src/main/res/drawable/bg_chip_feature.xml
  app/src/main/res/drawable/bg_edit_text_description.xml
  app/src/main/res/drawable/bg_radio_button_center.xml
  app/src/main/res/drawable/bg_radio_button_left.xml
  app/src/main/res/drawable/bg_radio_button_right.xml
  app/src/main/res/drawable/bg_radius_8_g3.xml
  app/src/main/res/drawable/bg_report_item_default.xml
  app/src/main/res/drawable/bg_top_radius_20_main_color.xml
  app/src/main/res/drawable/bg_top_radius_8_white.xml
  app/src/main/res/drawable/icon_report_arrow_down_16_g5.xml
  app/src/main/res/drawable/icon_report_arrow_right_13.xml
  app/src/main/res/drawable/icon_report_camera.xml
  app/src/main/res/drawable/icon_report_close_18.xml
  app/src/main/res/drawable/icon_report_location_map_orange.xml
  app/src/main/res/drawable/img_sample_dog.png
  app/src/main/res/layout/fragment_missing_repost.xml
  app/src/main/res/layout/fragment_witness_report.xml
  app/src/main/res/layout/item_feature_chip.xml
  app/src/main/res/layout/item_report_breeds.xml
  app/src/main/res/layout/item_report_colors.xml
  app/src/main/res/layout/item_report_default_image.xml
  app/src/main/res/layout/item_report_uploaded_image.xml
  app/src/main/res/values/strings.xml
Labels: 🐾익성, feat

#22 [feat] 신고하기 다이얼로그 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/assets/html/address.html
  app/src/main/java/com/example/findu/presentation/ui/report/ReportLocationActivity.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportFinishDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportImageDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportLocationDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportNavigationDialog.kt
  app/src/main/res/drawable/bg_button_report_dialog.xml
  app/src/main/res/drawable/bg_container_report_nav.xml
  app/src/main/res/drawable/bg_report_dialog_rd12.xml
  app/src/main/res/drawable/bg_report_dialog_rd8.xml
  app/src/main/res/drawable/ic_location_pin.xml
  app/src/main/res/drawable/ic_report_arrow_right_14.xml
  app/src/main/res/drawable/ic_report_dialog_call_green.xml
  app/src/main/res/drawable/ic_report_dialog_close_10.xml
  app/src/main/res/drawable/ic_report_dialog_write_blue.xml
  app/src/main/res/drawable/ic_report_dialog_write_red.xml
  app/src/main/res/drawable/ic_report_location.xml
  app/src/main/res/drawable/ic_report_upload_20.xml
  app/src/main/res/layout/activity_report_location.xml
  app/src/main/res/layout/dialog_report_finished.xml
  app/src/main/res/layout/dialog_report_image.xml
  app/src/main/res/layout/dialog_report_location.xml
  app/src/main/res/layout/dialog_report_navigation.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🐾익성, feat
