Repository FindYou-Kuit/FindYou-Android, pull requests merged in 2025-02, with the labels that each got.

#26 [feat] 홈화면 dialog 구현
  app/src/main/java/com/example/findu/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/home/adapter/HomeBannerAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/home/dialog/HomeFindDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/home/dialog/HomeReportDetailDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/home/dialog/HomeReportDialog.kt
  app/src/main/res/drawable/ic_dialog_back.xml
  app/src/main/res/drawable/img_dialog_bell_yellow.png
  app/src/main/res/drawable/img_dialog_phone_green.png
  app/src/main/res/drawable/img_dialog_search_blue.png
  app/src/main/res/layout/dialog_home_find.xml
  app/src/main/res/layout/dialog_home_report.xml
  app/src/main/res/layout/dialog_home_report_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_rv.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 🐻민서, feat

#27 [feat] 신고 네비게이션 기능 및 지도, 위치 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/findu/presentation/ui/home/dialog/HomeReportDetailDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/home/dialog/HomeReportDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/example/findu/presentation/ui/report/MissingReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/ReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/WitnessReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportFinishDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportImageDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportLocationActivity.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportLocationDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportNavigationDialog.kt
  app/src/main/java/com/example/findu/presentation/util/PermissionUtils.kt
  app/src/main/java/com/example/findu/presentation/util/ViewUtils.kt
  app/src/main/res/color/button_confirm_color.xml
  app/src/main/res/color/text_confirm_color.xml
  app/src/main/res/drawable/bg_button_report_confirm.xml
  app/src/main/res/layout/activity_report_location.xml
  app/src/main/res/layout/dialog_report_location.xml
  app/src/main/res/layout/dialog_report_navigation.xml
  app/src/main/res/layout/fragment_missing_report.xml
  app/src/main/res/layout/fragment_witness_report.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🐾익성, feat

#34 [feat] Gpt 로 동물 이미지 인식 기능 구현
  app/build.gradle.kts
  app/src/main/java/com/example/findu/data/dataremote/datasource/GptRemoteDataSource.kt
  app/src/main/java/com/example/findu/data/dataremote/datasourceimpl/GptRemoteDataSourceImpl.kt
  app/src/main/java/com/example/findu/data/dataremote/model/request/GptRequestDto.kt
  app/src/main/java/com/example/findu/data/dataremote/model/response/GptResponseDto.kt
  app/src/main/java/com/example/findu/data/dataremote/service/GptService.kt
  app/src/main/java/com/example/findu/data/mapper/toDomain/GptResponseDtoMapper.kt
  app/src/main/java/com/example/findu/data/repositoryimpl/ReportRepositoryImpl.kt
  app/src/main/java/com/example/findu/di/DataSourceModule.kt
  app/src/main/java/com/example/findu/di/NetworkModule.kt
  app/src/main/java/com/example/findu/di/RepositoryModule.kt
  app/src/main/java/com/example/findu/di/ServiceModule.kt
  app/src/main/java/com/example/findu/di/UseCaseModule.kt
  app/src/main/java/com/example/findu/domain/model/report/Breed.kt
  app/src/main/java/com/example/findu/domain/model/report/FurColorType.kt
  app/src/main/java/com/example/findu/domain/model/report/GptData.kt
  app/src/main/java/com/example/findu/domain/model/report/SpeciesType.kt
  app/src/main/java/com/example/findu/domain/repository/report/ReportRepository.kt
  app/src/main/java/com/example/findu/domain/usecase/report/AnalysisImageWithGptUseCase.kt
  app/src/main/java/com/example/findu/presentation/ui/report/MissingReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/ReportViewModel.kt
  app/src/main/java/com/example/findu/presentation/ui/report/WitnessReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportColorAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportImageAdapter.kt
  app/src/main/java/com/example/findu/presentation/util/UriUtil.kt
Labels: 🐾익성, feat

#38 [feat] 품종 Api 구현
  app/src/main/java/com/example/findu/data/dataremote/datasource/BreedRemoteDataSource.kt
  app/src/main/java/com/example/findu/data/dataremote/datasourceimpl/BreedRemoteDataSourceImpl.kt
  app/src/main/java/com/example/findu/data/dataremote/model/response/breed/BreedResponseDto.kt
  app/src/main/java/com/example/findu/data/dataremote/service/BreedService.kt
  app/src/main/java/com/example/findu/data/mapper/toDomain/GptResponseDtoMapper.kt
  app/src/main/java/com/example/findu/data/mapper/todomain/breed/BreedResponseDtoMapper.kt
  app/src/main/java/com/example/findu/data/repositoryimpl/BreedRepositoryImpl.kt
  app/src/main/java/com/example/findu/di/DataSourceModule.kt
  app/src/main/java/com/example/findu/di/RepositoryModule.kt
  app/src/main/java/com/example/findu/di/ServiceModule.kt
  app/src/main/java/com/example/findu/di/UseCaseModule.kt
  app/src/main/java/com/example/findu/domain/model/breed/BreedData.kt
  app/src/main/java/com/example/findu/domain/model/breed/BreedValidationData.kt
  app/src/main/java/com/example/findu/domain/model/breed/SpeciesType.kt
  app/src/main/java/com/example/findu/domain/model/report/Breed.kt
  app/src/main/java/com/example/findu/domain/model/report/GptData.kt
  app/src/main/java/com/example/findu/domain/repository/BreedRepository.kt
  app/src/main/java/com/example/findu/domain/usecase/GetBreedDataUseCase.kt
  app/src/main/java/com/example/findu/domain/usecase/GetBreedValidationUseCase.kt
  app/src/main/java/com/example/findu/presentation/model/GptUiState.kt
  app/src/main/java/com/example/findu/presentation/ui/report/MissingReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/ReportViewModel.kt
  app/src/main/java/com/example/findu/presentation/ui/report/WitnessReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportBreedAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportColorAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/report/constants/ReportConstants.kt
  app/src/main/res/layout/fragment_witness_report.xml
  app/src/main/res/values/strings.xml
Labels: 🐾익성, feat

#35 [feat] 사진 촬영 , 업로드 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/findu/presentation/ui/report/MissingReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/ReportCameraFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/ReportViewModel.kt
  app/src/main/java/com/example/findu/presentation/ui/report/WitnessReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportImageAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportImageDialog.kt
  app/src/main/java/com/example/findu/presentation/util/PermissionUtils.kt
  app/src/main/res/layout/fragment_report_camera.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🐾익성, feat

#39 [Feat] 정보화면 UI 구현
  .idea/misc.xml
  app/src/main/java/com/example/findu/presentation/model/InfoRv.kt
  app/src/main/java/com/example/findu/presentation/ui/info/AdoptInfoFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/info/InfoFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/info/InfoRvAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/info/InfoViewModel.kt
  app/src/main/java/com/example/findu/presentation/ui/info/ReportInfoFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/info/VolunteerInfoFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/MissingReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/WitnessReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportImageAdapter.kt
  app/src/main/res/drawable/bg_blue_talk_box.png
  app/src/main/res/drawable/bg_radius_10_gray.xml
  app/src/main/res/drawable/bg_radius_10_info_orange.xml
  app/src/main/res/drawable/bg_radius_10_orange.xml
  app/src/main/res/drawable/bg_radius_20_orange.xml
  app/src/main/res/drawable/bg_top_radius_18_white.xml
  app/src/main/res/drawable/bg_yellow_talk_box.png
  app/src/main/res/drawable/ic_info_navigate.xml
  app/src/main/res/drawable/img_adopt_info.png
  app/src/main/res/drawable/img_report_info.png
  app/src/main/res/drawable/img_volunteer_info.png
  app/src/main/res/layout/fragment_adopt_info.xml
  app/src/main/res/layout/fragment_info.xml
  app/src/main/res/layout/fragment_report_info.xml
  app/src/main/res/layout/fragment_volunteer_info.xml
  app/src/main/res/layout/item_info_rv.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🐻민서, feat

#49 [Chore] log, runcatching 형식 통일
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/findu/data/dataremote/datasourceimpl/NaverRemoteDataSourceImpl.kt
  app/src/main/java/com/example/findu/data/repositoryimpl/ReportRepositoryImpl.kt
  app/src/main/java/com/example/findu/presentation/ui/report/WitnessReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/dialog/ReportLocationDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/report/viewmodel/LocationViewModel.kt
  app/src/main/java/com/example/findu/presentation/ui/report/viewmodel/ReportViewModel.kt
Labels: 🐾익성, chore

#55 [Feat] 로그인, 회원가입 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/findu/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/example/findu/presentation/ui/signup/SignupActivity.kt
  app/src/main/java/com/example/findu/presentation/ui/signup/SignupSuccessActivity.kt
  app/src/main/java/com/example/findu/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/bg_edittext.xml
  app/src/main/res/drawable/ic_login_email.xml
  app/src/main/res/drawable/ic_login_password.xml
  app/src/main/res/drawable/ic_password_off.xml
  app/src/main/res/drawable/ic_password_on.xml
  app/src/main/res/drawable/img_findu_text_logo.png
  app/src/main/res/drawable/img_kakao_login.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/activity_signup_success.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/strings.xml
Labels: 🐻민서, feat

#50 [Feat] 마이페이지 Api 구현
  app/src/main/java/com/example/findu/data/dataremote/datasource/MyRemoteDataSource.kt
  app/src/main/java/com/example/findu/data/dataremote/datasourceimpl/MyRemoteDataSourceImpl.kt
  app/src/main/java/com/example/findu/data/dataremote/model/response/my/MyInterestResponseDto.kt
  app/src/main/java/com/example/findu/data/dataremote/model/response/my/MyNickNameResponseDto.kt
  app/src/main/java/com/example/findu/data/dataremote/model/response/my/MyReportHistoryResponseDto.kt
  app/src/main/java/com/example/findu/data/dataremote/model/response/my/MyViewedAnimalsResponseDto.kt
  app/src/main/java/com/example/findu/data/dataremote/service/MyService.kt
  app/src/main/java/com/example/findu/data/mapper/toDomain/my/MyResponseDtoMapper.kt
  app/src/main/java/com/example/findu/data/repositoryimpl/MyRepositoryImpl.kt
  app/src/main/java/com/example/findu/di/DataSourceModule.kt
  app/src/main/java/com/example/findu/di/RepositoryModule.kt
  app/src/main/java/com/example/findu/di/ServiceModule.kt
  app/src/main/java/com/example/findu/di/UseCaseModule.kt
  app/src/main/java/com/example/findu/domain/model/my/MyInterestData.kt
  app/src/main/java/com/example/findu/domain/model/my/MyReportHistoryData.kt
  app/src/main/java/com/example/findu/domain/model/my/MyViewedAnimalData.kt
  app/src/main/java/com/example/findu/domain/repository/MyRepository.kt
  app/src/main/java/com/example/findu/domain/usecase/my/DeleteUserUseCase.kt
  app/src/main/java/com/example/findu/domain/usecase/my/GetInterestUseCase.kt
  app/src/main/java/com/example/findu/domain/usecase/my/GetNickNameUseCase.kt
  app/src/main/java/com/example/findu/domain/usecase/my/GetReportHistoryUseCase.kt
  app/src/main/java/com/example/findu/domain/usecase/my/GetViewedAnimalUseCase.kt
  app/src/main/java/com/example/findu/domain/usecase/my/PatchNickNameUseCase.kt
  app/src/main/java/com/example/findu/presentation/mapper/torvmodel/MyInterestDataMapper.kt
  app/src/main/java/com/example/findu/presentation/model/MyRv.kt
  app/src/main/java/com/example/findu/presentation/ui/my/MyFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/my/MyInterestFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/my/MyReportHistoryFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/my/MyViewModel.kt
  app/src/main/java/com/example/findu/presentation/ui/my/MyViewedAnimalFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/my/adapter/MyInterestRvAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/my/adapter/MyReportHistoryAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/my/adapter/MyViewedAnimalsRvAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/report/ReportCameraFragment.kt
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_my_interest.xml
  app/src/main/res/layout/fragment_my_report_history.xml
  app/src/main/res/layout/fragment_my_viewed_animal.xml
  app/src/main/res/layout/item_my_history.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🐾익성, feat, no merge

#54 [Refactor] gpt prompt 수정
  app/build.gradle.kts
  app/src/main/java/com/example/findu/data/dataremote/model/request/GptRequestDto.kt
  app/src/main/java/com/example/findu/data/repositoryimpl/ReportRepositoryImpl.kt
  app/src/main/java/com/example/findu/domain/repository/report/ReportRepository.kt
  app/src/main/java/com/example/findu/domain/usecase/report/AnalysisImageWithGptUseCase.kt
  app/src/main/java/com/example/findu/presentation/ui/report/MissingReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/WitnessReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/adapter/ReportImageAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/report/viewmodel/ReportViewModel.kt
  app/src/main/res/layout/fragment_missing_report.xml
  app/src/main/res/layout/fragment_witness_report.xml
  app/src/main/res/raw/loading_animation.json
  gradle/libs.versions.toml
Labels: 🐾익성, feat, refactor

#57 [Feat] 홈, 정보 화면 이동 기능 추가
  app/src/main/java/com/example/findu/presentation/model/HomeRv.kt
  app/src/main/java/com/example/findu/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/home/adapter/HomeRVAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/home/dialog/HomeFindDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/home/dialog/HomeReportDetailDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/home/dialog/HomeReportDialog.kt
  app/src/main/java/com/example/findu/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/example/findu/presentation/ui/info/ReportInfoFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/search/SearchFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🐻민서, feat

#59 [feat] 조회 페이징 기능 추가 , 신고 네비게이션 기능 수정
  app/src/main/java/com/example/findu/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/example/findu/presentation/ui/report/MissingReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/report/WitnessReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/search/SearchFilterBottomSheet.kt
  app/src/main/java/com/example/findu/presentation/ui/search/adapter/SearchContentRVAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/search/tablayout/SearchAllFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/search/tablayout/SearchReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/search/tablayout/SearchRescueFragment.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_missing_report.xml
  app/src/main/res/layout/fragment_search_filter_bottom_sheet.xml
  app/src/main/res/layout/fragment_search_report.xml
  app/src/main/res/layout/fragment_witness_report.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: 🐾익성, feat

#61 [feat] 마이페이지 관심동물 등록 & 상세 페이지 이동
  app/build.gradle.kts
  app/src/main/java/com/example/findu/data/dataremote/datasource/ReportRemoteDataSource.kt
  app/src/main/java/com/example/findu/data/dataremote/datasourceimpl/ReportRemoteDataSourceImpl.kt
  app/src/main/java/com/example/findu/data/dataremote/service/ReportService.kt
  app/src/main/java/com/example/findu/data/repositoryimpl/ReportRepositoryImpl.kt
  app/src/main/java/com/example/findu/di/UseCaseModule.kt
  app/src/main/java/com/example/findu/domain/repository/report/ReportRepository.kt
  app/src/main/java/com/example/findu/domain/usecase/report/DeleteReportUseCase.kt
  app/src/main/java/com/example/findu/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/example/findu/presentation/ui/my/MyInterestFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/my/MyReportHistoryFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/my/MyViewModel.kt
  app/src/main/java/com/example/findu/presentation/ui/my/MyViewedAnimalFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/my/adapter/MyInterestRvAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/my/adapter/MyReportHistoryAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/my/adapter/MyViewedAnimalsRvAdapter.kt
  app/src/main/java/com/example/findu/presentation/ui/search/SearchFilterBottomSheet.kt
  app/src/main/java/com/example/findu/presentation/ui/search/detail/SearchDisappearDetailFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/search/detail/SearchProtectingDetailFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/search/detail/SearchWitnessDetailFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/search/tablayout/SearchAllFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/search/tablayout/SearchReportFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/search/tablayout/SearchRescueFragment.kt
  app/src/main/java/com/example/findu/presentation/ui/search/viewmodel/SearchViewModel.kt
  app/src/main/java/com/example/findu/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_search_detail_disappear.xml
  app/src/main/res/layout/fragment_search_detail_protecting.xml
  app/src/main/res/layout/fragment_search_detail_witness.xml
  app/src/main/res/navigation/nav_graph.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🐾익성, feat
